[package]
name = "ic-md"
version = "0.1.0"
authors = ["Reto Trappitsch <reto@galactic-forensics.space>"]
license = "MIT OR Apache-2.0"
edition = "2024"
description = "Driver for the iC-Haus iC-MD 48-Bit quadrature counter with SPI interface."
documentation = "https://docs.rs/ic-md"
repository = "https://github.com/trappitsch/ic-md"

[dependencies]
defmt = { version = "1", optional = true }
device-driver = { version = "2", features = ["macros"] }
embedded-hal = "1"
embedded-hal-async = "1"

[features]
async = []
blocking = []
default = ["blocking"]
defmt = ["dep:defmt"]

[dev-dependencies]
embedded-hal-mock = "0.11.1"
pico-de-gallo-hal = "0.7.0"

[[example]]
name = "counter_readout"
required-features = ["blocking"]

[[test]]
name = "configure_counter"
required-features = ["blocking"]

[[test]]
name = "negative_numbers"
required-features = ["blocking"]

[[test]]
name = "simple"
required-features = ["blocking"]

[[test]]
name = "status"
required-features = ["blocking"]
