[package]
name = "rp235x_three_ttl"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m            = { version = "0.7.6", features = ["inline-asm"] }
embassy-executor    = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-rp          = { version = "0.8.0", features = ["rp235xa", "defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embassy-time        = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime"] }
panic-probe         = { version = "0.3",   features = ["print-defmt"] }
embedded-hal        = "1.0.0"
embassy-futures     = "0.1.2"
cortex-m-rt         = "0.7.5"
defmt               = "1.0.1"
defmt-rtt           = "1.0.0"
static_cell         = "2.1.1"
embassy-sync        = "0.7.0"

ic-md               = { path = "../../", version = "0.1.0", features = ["defmt"] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }

[profile.release]
debug = 2
lto = true
opt-level = 'z'
codegen-units = 1
incremental = false

[profile.ci]
inherits = "dev"
debug = false
strip = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = false
codegen-units = 256
rpath = false
